### ISSUE TITLE
Обеспечить совместимость с android версии < 5.0

### ISSUE THREAD

**Issue by igorcoding** [tech-team/decider-android#39]
```
07-17 22:45:12.374 9465-9465/org.techteam.decider E/AndroidRuntime﹕ FATAL EXCEPTION: main
Process: org.techteam.decider, PID: 9465
java.lang.ClassCastException: android.graphics.drawable.ColorDrawable cannot be cast to android.support.v7.widget.RoundRectDrawableWithShadow
at android.support.v7.widget.CardViewEclairMr1.getShadowBackground(CardViewEclairMr1.java:159)
at android.support.v7.widget.CardViewEclairMr1.getMinWidth(CardViewEclairMr1.java:150)
at android.support.v7.widget.CardView.onMeasure(CardView.java:181)
at android.view.View.measure(View.java:17387)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5352)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
at android.view.View.measure(View.java:17387)
at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1237)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:590)
at android.view.View.measure(View.java:17387)
at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
at android.view.View.measure(View.java:17387)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5352)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
at android.view.View.measure(View.java:17387)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5352)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
at android.support.v7.widget.CardView.onMeasure(CardView.java:196)
at android.view.View.measure(View.java:17387)
at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:5857)
at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1337)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1274)
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:525)
at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2118)
at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2415)
at android.view.View.layout(View.java:15655)
at android.view.ViewGroup.layout(ViewGroup.java:4856)
at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:562)
at android.view.View.layout(View.java:15655)
at android.view.ViewGroup.layout(ViewGroup.java:4856)
at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1593)
at android.view.View.layout(View.java:15655)
at android.view.ViewGroup.layout(ViewGroup.java:4856)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
at android.view.View.layout(View.java:15655)
at android.view.ViewGroup.layout(ViewGroup.java:4856)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:15655)
at android.view.ViewGroup.layout(ViewGroup.java:4856)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
at android.view.View.layout(View.java:15655)
at android.view.ViewGroup.layout(ViewGroup.java:4856)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:15655)
at android.view.ViewGroup.layout(ViewGroup.java:4856)
at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:907)
at android.view.View.layout(View.java:15655)
at android.view.ViewGroup.layout(ViewGroup.java:4856)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:15655)
at
```

```
07-17 22:54:32.400 12878-12878/org.techteam.decider I/dalvikvm﹕ Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.internal.widget.TintTypedArray.getChangingConfigurations
07-17 22:54:32.400 12878-12878/org.techteam.decider W/dalvikvm﹕ VFY: unable to resolve virtual method 700: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
07-17 22:54:32.400 12878-12878/org.techteam.decider D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0002
07-17 22:54:32.400 12878-12878/org.techteam.decider I/dalvikvm﹕ Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.internal.widget.TintTypedArray.getType
07-17 22:54:32.410 12878-12878/org.techteam.decider W/dalvikvm﹕ VFY: unable to resolve virtual method 722: Landroid/content/res/TypedArray;.getType (I)I
07-17 22:54:32.410 12878-12878/org.techteam.decider D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0002
07-17 22:54:32.560 12878-12878/org.techteam.decider W/dalvikvm﹕ Unable to resolve superclass of Lcom/mikepenz/materialdrawer/view/BezelImageView$CustomOutline; (1901)
07-17 22:54:32.560 12878-12878/org.techteam.decider W/dalvikvm﹕ Link of class 'Lcom/mikepenz/materialdrawer/view/BezelImageView$CustomOutline;' failed
07-17 22:54:32.560 12878-12878/org.techteam.decider E/dalvikvm﹕ Could not find class 'com.mikepenz.materialdrawer.view.BezelImageView$CustomOutline', referenced from method com.mikepenz.materialdrawer.view.BezelImageView.onSizeChanged
07-17 22:54:32.560 12878-12878/org.techteam.decider W/dalvikvm﹕ VFY: unable to resolve new-instance 7352 (Lcom/mikepenz/materialdrawer/view/BezelImageView$CustomOutline;) in Lcom/mikepenz/materialdrawer/view/BezelImageView;
07-17 22:54:32.560 12878-12878/org.techteam.decider D/dalvikvm﹕ VFY: replacing opcode 0x22 at 0x0006
07-17 22:54:32.560 12878-12878/org.techteam.decider W/dalvikvm﹕ Unable to resolve superclass of Lcom/mikepenz/materialdrawer/view/BezelImageView$CustomOutline; (1901)
07-17 22:54:32.560 12878-12878/org.techteam.decider W/dalvikvm﹕ Link of class 'Lcom/mikepenz/materialdrawer/view/BezelImageView$CustomOutline;' failed
07-17 22:54:32.560 12878-12878/org.techteam.decider D/dalvikvm﹕ DexOpt: unable to opt direct call 0xc5b9 at 0x08 in Lcom/mikepenz/materialdrawer/view/BezelImageView;.onSizeChanged
07-17 22:54:32.610 12878-12878/org.techteam.decider I/dalvikvm﹕ Could not find method android.content.res.Resources.getDrawable, referenced from method com.mikepenz.materialdrawer.util.UIUtils.getCompatDrawable
```

**Comment by alekseyl1992** [comment]
Это в профиле чтоль из-за тени?
Или тут вообще несколько кейсов описано?

**Comment by igorcoding** [comment]
Первый лог - из-за этого приложение падает, второй - просто обнаружено в логах

**Comment by Abashinos** [comment]
У меня приложение падает на главном экране (с вопросами). В дебаге вот эта единственная ошибка

**Comment by alekseyl1992** [comment]
Во втором логе речь про
com/mikepenz/materialdrawer
будет весело откатываться на свой дровер...
завтра гляну, на сколько всё серьёзно

**Comment by igorcoding** [comment]
Считаем, что пофикшено
