### ISSUE TITLE
Двухэтапная регистрация

### ISSUE THREAD

**Issue by igorcoding** [tech-team/decider-android#47]
см. https://github.com/tech-team/decider-backend/issues/11

**Comment by alekseyl1992** [comment]
Разобраться с падением в случае соц. регистрации:

```
07-22 21:16:31.608  13401-13423/org.techteam.decider D/org.techteam.decider.auth.AccountAuthenticator﹕ > getAuthToken
07-22 21:16:31.610  13401-13423/org.techteam.decider D/org.techteam.decider.auth.AccountAuthenticator﹕ > peekAuthToken returned - null
07-22 21:16:31.613  13401-15074/org.techteam.decider W/System.err﹕ org.techteam.decider.rest.api.InvalidAccessTokenException: Access token is invalid.
07-22 21:16:31.614  13401-15074/org.techteam.decider W/System.err﹕ at org.techteam.decider.rest.api.ApiUI.prepareHttpRequest(ApiUI.java:324)
07-22 21:16:31.614  13401-15074/org.techteam.decider W/System.err﹕ at org.techteam.decider.rest.api.ApiUI.makeProtectedPostCall(ApiUI.java:380)
07-22 21:16:31.614  13401-15074/org.techteam.decider W/System.err﹕ at org.techteam.decider.rest.api.ApiUI.authPush(ApiUI.java:313)
07-22 21:16:31.614  13401-15074/org.techteam.decider W/System.err﹕ at org.techteam.decider.rest.processors.PushAuthProcessor.executeRequest(PushAuthProcessor.java:37)
07-22 21:16:31.614  13401-15074/org.techteam.decider W/System.err﹕ at org.techteam.decider.rest.processors.RequestProcessor.start(RequestProcessor.java:62)
07-22 21:16:31.614  13401-15074/org.techteam.decider W/System.err﹕ at org.techteam.decider.gcm.GcmRegistrationIntentService.sendRegistrationToServer(GcmRegistrationIntentService.java:87)
07-22 21:16:31.614  13401-15074/org.techteam.decider W/System.err﹕ at org.techteam.decider.gcm.GcmRegistrationIntentService.onHandleIntent(GcmRegistrationIntentService.java:54)
07-22 21:16:31.614  13401-15074/org.techteam.decider W/System.err﹕ at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
07-22 21:16:31.614  13401-15074/org.techteam.decider W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
07-22 21:16:31.614  13401-15074/org.techteam.decider W/System.err﹕ at android.os.Looper.loop(Looper.java:211)
07-22 21:16:31.614  13401-15074/org.techteam.decider W/System.err﹕ at android.os.HandlerThread.run(HandlerThread.java:61)
07-22 21:16:31.631  13401-13401/org.techteam.decider D/AndroidRuntime﹕ Shutting down VM
07-22 21:16:31.631  13401-13401/org.techteam.decider E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.techteam.decider, PID: 13401
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.BroadcastReceiver.onReceive(android.content.Context, android.content.Intent)' on a null object reference
            at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
            at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
            at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:211)
            at android.app.ActivityThread.main(ActivityThread.java:5321)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

**Comment by igorcoding** [comment]
Вроде бы все реализовано, просьба проверить.

**Comment by alekseyl1992** [comment]
Зарегался через ВК
написал коммент (классная анимашка добавления порадовала).
нажал назад
начать скроллить
и оно упало:

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
            at android.os.BaseBundle.getInt(BaseBundle.java:800)
            at org.techteam.decider.gcm.data.PushParser.parse(PushParser.java:7)
            at org.techteam.decider.gcm.DeciderGcmListenerService.onMessageReceived(DeciderGcmListenerService.java:35)
```

**Comment by alekseyl1992** [comment]
потом

```
07-23 12:26:33.388  17826-19939/org.techteam.decider E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #5
    Process: org.techteam.decider, PID: 17826
    java.lang.RuntimeException: Unknown push code: -1
            at org.techteam.decider.gcm.data.PushCode.fromCode(PushCode.java:25)
            at org.techteam.decider.gcm.data.PushParser.parse(PushParser.java:8)
            at org.techteam.decider.gcm.DeciderGcmListenerService.onMessageReceived(DeciderGcmListenerService.java:35)
```

**Comment by alekseyl1992** [comment]
потом

```
07-23 12:26:33.389  17826-19938/org.techteam.decider I/Process﹕ Sending signal. PID: 17826 SIG: 9
07-23 12:27:21.066  23257-23257/org.techteam.decider W/ResourceType﹕ Found multiple library tables, ignoring...
07-23 12:27:21.163  23257-23285/org.techteam.decider I/org.techteam.decider.gcm.DeciderGcmListenerService﹕ From: 620471085989
07-23 12:27:21.166  23257-23285/org.techteam.decider I/org.techteam.decider.gcm.DeciderGcmListenerService﹕ Message: Bundle[{code=1000, comment_id=181, question_id=50, collapse_key=do_not_collapse}]
07-23 12:27:21.167  23257-23286/org.techteam.decider I/org.techteam.decider.gcm.DeciderGcmListenerService﹕ From: 620471085989
07-23 12:27:21.169  23257-23285/org.techteam.decider W/Bundle﹕ Key code expected Integer but value was a java.lang.String.  The default value -1 was returned.
07-23 12:27:21.170  23257-23285/org.techteam.decider W/Bundle﹕ Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
            at android.os.BaseBundle.getInt(BaseBundle.java:800)
            at org.techteam.decider.gcm.data.PushParser.parse(PushParser.java:7)
            at org.techteam.decider.gcm.DeciderGcmListenerService.onMessageReceived(DeciderGcmListenerService.java:35)
```

**Comment by alekseyl1992** [comment]
и потом

```
07-23 12:27:21.174  23257-23285/org.techteam.decider E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #1
    Process: org.techteam.decider, PID: 23257
    java.lang.RuntimeException: Unknown push code: -1
            at org.techteam.decider.gcm.data.PushCode.fromCode(PushCode.java:25)
            at org.techteam.decider.gcm.data.PushParser.parse(PushParser.java:8)
            at org.techteam.decider.gcm.DeciderGcmListenerService.onMessageReceived(DeciderGcmListenerService.java:35)
```

**Comment by alekseyl1992** [comment]
В общем проблема, очевидно не с регой
по этому эту я закрываю и линкую из issue про Пуши: https://github.com/tech-team/decider-android/issues/8
