### ISSUE TITLE
Падение после создания поста

### ISSUE THREAD

**Issue by igorcoding** [tech-team/decider-android#64]
Создал пост, редиректнуло на него, нажал назад, обновил список.

```
07-20 18:38:35.267    6914-6914/org.techteam.decider E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.techteam.decider, PID: 6914
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
            at org.techteam.decider.gui.adapters.QuestionsListAdapter.updateLoadingEntry(QuestionsListAdapter.java:117)
            at org.techteam.decider.gui.adapters.QuestionsListAdapter.setFeedFinished(QuestionsListAdapter.java:110)
            at org.techteam.decider.gui.fragments.QuestionsListFragment$2.onSuccess(QuestionsListFragment.java:156)
            at org.techteam.decider.rest.service_helper.ServiceHelper$ServiceBroadcastReceiver.onReceive(ServiceHelper.java:313)
            at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
            at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
            at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

```

**Comment by igorcoding** [comment]
Вроде пофиксил в 70c3491fb8c45b4e9971a98f702522539444b043
