### ISSUE TITLE
Падение после фотографирования камерой

### ISSUE THREAD

**Issue by igorcoding** [tech-team/decider-android#65]
```
07-20 18:37:22.566    5314-5314/org.techteam.decider E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.techteam.decider, PID: 5314
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=257, result=-1, data=Intent {  }} to activity {org.techteam.decider/org.techteam.decider.gui.activities.AddQuestionActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3574)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617)
            at android.app.ActivityThread.access$1300(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
            at android.content.ContentResolver.openInputStream(ContentResolver.java:630)
            at org.techteam.decider.util.image_selector.ImageSelector.fixUri(ImageSelector.java:199)
            at org.techteam.decider.util.image_selector.ImageSelector.onActivityResult(ImageSelector.java:124)
            at org.techteam.decider.gui.activities.AddQuestionActivity.onActivityResult(AddQuestionActivity.java:194)
            at android.app.Activity.dispatchActivityResult(Activity.java:6192)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617)
            at android.app.ActivityThread.access$1300(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by igorcoding** [comment]
ok

**Comment by alekseyl1992** [comment]
Closed in https://github.com/tech-team/decider-android/commit/c2bdbd81feb5acda62d056dd4839698b5a52560e
