### ISSUE TITLE
Зайти через ВК, выйти и зайти через ВК

### ISSUE THREAD

**Issue by alekseyl1992** [tech-team/decider-android#83]
```
    Process: org.techteam.decider, PID: 28407
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.BroadcastReceiver.onReceive(android.content.Context, android.content.Intent)' on a null object reference
            at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
            at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
            at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:211)
            at android.app.ActivityThread.main(ActivityThread.java:5321)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

**Comment by igorcoding** [comment]
Проблема не только с вк
Иногда, подчеркваю - иногда, при логауте в одном из QuestionsListFragment'е (чаще всего Popular) срабатывает onScrolledDown и он пытается полезть в сеть, но токена нет, поэтому он фейлится и запрашивает getAuthToken, хотя его запросил уже тот кусок, что выполнял логаут, т.е. AuthActivity открывается дважды. Далее, по завершении, андроид, кажется, не может разобраться, что ему делать, и оно падает с ошибкой выше.

Кроме того, иногда при попытке логаута (чаще всего именно это и предвещает будущее падение) появляется такое исключение:

```
07-24 03:09:40.822  29444-29444/org.techteam.decider E/ActivityThread﹕ Performing stop of activity that is not resumed: {org.techteam.decider/org.techteam.decider.gui.activities.MainActivity}
    java.lang.RuntimeException: Performing stop of activity that is not resumed: {org.techteam.decider/org.techteam.decider.gui.activities.MainActivity}
            at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3344)
            at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3425)
            at android.app.ActivityThread.access$1100(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

Что с ним делать - я так и не понял...

в общем, я пока закостылил, так, чтобы если текущую вкладку не видно - у нее не срабатывал бы onScrollDown (почему он срабатывает мне тоже интересно):

``` java
@Override
public void onScrolledDown() {
    MainFragment mainFragment = activity.getMainFragment();
    if (mainFragment.getCurrentlyActiveFragment() == this) {
        int intention;
        if (adapter.getCursor().getCount() == 0) {
            intention = LoadIntention.REFRESH;
        } else {
            intention = LoadIntention.APPEND;
        }

        serviceHelper.getQuestions(currentSection,
                QUESTIONS_LIMIT,
                questionsOffset,
                activity.getSelectedCategories(),
                intention,
                callbacksKeeper.getCallback(OperationType.QUESTIONS_GET));
    }
}
```

**Comment by igorcoding** [comment]
случайно закрыл

**Comment by alekseyl1992** [comment]
Ещё как вариант - можно убить текущий процесс после логаута.
Раз уж recreate() не работает нормально.
