### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by igorcoding** [tech-team/decider-android#84]
```
07-24 17:00:30.325    2476-2884/org.techteam.decider E/dalvikvm-heap﹕ Out of memory on a 1166416-byte allocation.
07-24 17:00:30.325    2476-2884/org.techteam.decider I/dalvikvm﹕ "uil-pool-2-thread-2" prio=4 tid=16 RUNNABLE
07-24 17:00:30.325    2476-2884/org.techteam.decider I/dalvikvm﹕ | group="main" sCount=0 dsCount=0 obj=0x4257c250 self=0x59912008
07-24 17:00:30.325    2476-2884/org.techteam.decider I/dalvikvm﹕ | sysTid=2884 nice=10 sched=0/0 cgrp=apps/bg_non_interactive handle=1502686560
07-24 17:00:30.325    2476-2884/org.techteam.decider I/dalvikvm﹕ | state=R schedstat=( 1845928297 914702914 18634 ) utm=146 stm=38 core=0
07-24 17:00:30.325    2476-2884/org.techteam.decider I/dalvikvm﹕ at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
07-24 17:00:30.325    2476-2884/org.techteam.decider I/dalvikvm﹕ at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:623)
07-24 17:00:30.325    2476-2884/org.techteam.decider I/dalvikvm﹕ at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:78)
07-24 17:00:30.325    2476-2884/org.techteam.decider I/dalvikvm﹕ at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(LoadAndDisplayImageTask.java:264)
07-24 17:00:30.330    2476-2884/org.techteam.decider I/dalvikvm﹕ at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:222)
07-24 17:00:30.330    2476-2884/org.techteam.decider I/dalvikvm﹕ at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:135)
07-24 17:00:30.330    2476-2884/org.techteam.decider I/dalvikvm﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
07-24 17:00:30.330    2476-2884/org.techteam.decider I/dalvikvm﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
07-24 17:00:30.330    2476-2884/org.techteam.decider I/dalvikvm﹕ at java.lang.Thread.run(Thread.java:841)
07-24 17:00:30.330    2476-2884/org.techteam.decider I/dalvikvm﹕ [ 07-24 17:00:30.330  2476: 2884 D/skia     ]
    --- decoder->decode returned false
07-24 17:00:30.350    2476-2884/org.techteam.decider E/ImageLoader﹕ null
    java.lang.OutOfMemoryError
            at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:623)
            at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:78)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(LoadAndDisplayImageTask.java:264)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:222)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:135)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
```

**Comment by igorcoding** [comment]
Еще другое исключение немного

```
07-24 17:35:02.661  12389-14162/org.techteam.decider E/art﹕ Throwing OutOfMemoryError "Failed to allocate a 3683532 byte allocation with 2422028 free bytes and 2MB until OOM"
07-24 17:35:02.666  12389-14295/org.techteam.decider E/art﹕ Throwing OutOfMemoryError "Failed to allocate a 3683532 byte allocation with 2421388 free bytes and 2MB until OOM"
07-24 17:35:02.666  12389-14162/org.techteam.decider D/skia﹕ --- decoder->decode returned false
07-24 17:35:02.666  12389-14292/org.techteam.decider E/ImageLoader﹕ Failed to allocate a 3683532 byte allocation with 2373316 free bytes and 2MB until OOM
    java.lang.OutOfMemoryError: Failed to allocate a 3683532 byte allocation with 2373316 free bytes and 2MB until OOM
            at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
            at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
            at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:773)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:749)
            at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:78)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(LoadAndDisplayImageTask.java:264)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:222)
            at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:135)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```
